BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "reservations" (
	"id_reservations"	SMALLINT UNSIGNED,
	"start"	DATETIME NOT NULL,
	"end"	DATETIME NOT NULL,
	"id_room"	SMALLINT UNSIGNED,
	FOREIGN KEY("id_room") REFERENCES "room"("id"),
	PRIMARY KEY("id_reservations")
);
CREATE TABLE IF NOT EXISTS "room" (
	"id"	SMALLINT UNSIGNED,
	"capacity"	SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY("id")
);
INSERT INTO "reservations" VALUES (1,'2022-03-23 10:00','2022-03-23 11:00',2);
INSERT INTO "reservations" VALUES (2,'2022-03-25 13:00','2022-03-25 14:00',4);
INSERT INTO "room" VALUES (2,4);
INSERT INTO "room" VALUES (3,8);
INSERT INTO "room" VALUES (4,6);
INSERT INTO "room" VALUES (1,4);
COMMIT;
